version: '3.8'
services:
  db:
    image: postgres
    container_name: better-auth
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nafiz
      POSTGRES_PASSWORD: secretPass
      POSTGRES_DB: nafizDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
